# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-30 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Math',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=50)),
                ('score', models.IntegerField(max_length=3)),
                ('teacher', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-score'],
                'db_table': 'math',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2, null=True)),
                ('grade', models.IntegerField(max_length=1)),
                ('s_class', models.CharField(max_length=50)),
                ('math', models.IntegerField(max_length=3)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2, null=True)),
                ('course', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=3)),
                ('join_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('introduction', models.TextField()),
            ],
            options={
                'db_table': 'teacher',
                'get_latest_by': 'join_date',
            },
        ),
    ]
