# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-30 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infomanage', '0002_auto_20180730_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='math',
            field=models.IntegerField(null=True),
        ),
    ]
