# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-30 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infomanage', '0004_auto_20180730_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='math',
            field=models.IntegerField(default=90),
        ),
    ]
